AirWaze/Entities/Plane.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AirWaze.Entities
{
    public class Plane
    {
        [Key]
        public int PlaneID { get; set; }
        public string PlaneNr { get; set; }

        public Airline CurrentAirline { get; set; }

        public int PassengerCapacity { get; set; }

        public decimal FuelCapacity { get; set; }

        public string Type { get; set; }

        public string Manufacturer { get; set; }

        public string FlightRegion { get; set; }

        public int FirstClassCapacity { get; set; }

        public decimal LoadCapacity { get; set; }

        public decimal FuelUsagePerKM { get; set; }
        
        public bool IsAvailable { get; set; }
        
        public string? SeatDiagramPic { get; set; }
        
        public DateTime ConstructionYear { get; set; }
        
        public int AirMiles { get; set; }
       
        public int FlightHours { get; set; }
        
        public int NextMainentance { get; set; }
    }
}

AirWaze/Controllers/PlaneController.cs
using AirWaze.Database.Design;
using AirWaze.Entities;
using AirWaze.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace AirWaze.Controllers
{
    public class PlaneController : Controller
    {

        private IAirWazeDatabase _myDatabase;

        public static List<PlaneCreateViewModel> planesToAdd = new List<PlaneCreateViewModel>();
              
        public static List<Plane> planeEntities = new List<Plane>();

        private static List<Airline> airlineEntities = new List<Airline>();

        private static List<string> regionList = new List<string>
        {
            "EUR","NA","SA","ASI","ME","AF","OC"
        };

        public static Airline LoggedInAirline;

        //Gets All Entities of Planes - Will do For all uses!
        public PlaneController(IAirWazeDatabase mydatabase)
        {
            List<Plane> oldlist = planeEntities.ToList();
            if (_myDatabase == null)
            {
                _myDatabase = mydatabase;               
            }
            planeEntities = _myDatabase.GetPlanes();
            foreach (Plane x in planeEntities)
            {
                foreach (Plane y in oldlist)
                {
                    if (x.PlaneID == y.PlaneID)
                    {
                        if (x.IsAvailable != y.IsAvailable)
                        {
                            x.IsAvailable = y.IsAvailable;
                            //_myDatabase.UpdatePlane(x);
                        }
                    }
                }
            }
            airlineEntities = _myDatabase.GetAirlines();
        }

        [Authorize(Roles = "Airline")]
        // AIRLINE ROLE
        [HttpGet]
        public async Task<IActionResult> Index(Guid ID)
        {          
            LoggedInAirline = airlineEntities.FirstOrDefault(x => x.AirlineID == ID);
            if (LoggedInAirline == null)
            {

                LoggedInAirline = new Airline
                {
                    Name = "Harald Airways",
                };
                LoggedInAirline =  airlineEntities.FirstOrDefault(x => x.Name == LoggedInAirline.Name);
               
            }

            if (LoggedInAirline.CurrentPlanes == null)
            {
                LoggedInAirline.CurrentPlanes = new List<Plane>();
            }
            List<Plane> planelistAirline = new List<Plane>();
            foreach (Plane x in planeEntities)
            {
                if (x.CurrentAirline.AirlineID == LoggedInAirline.AirlineID) 
                {
                    planelistAirline.Add(x);
                }
            }                 
            List<PlaneListViewModel> thislist = new List<PlaneListViewModel>();
            foreach (var plane in planelistAirline)
            {
               thislist.Add(new PlaneListViewModel()
                {
                    PlaneNr = plane.PlaneNr,
                    CurrentAirline = plane.CurrentAirline,
                    PassengerCapacity = plane.PassengerCapacity,
                    FlightRegion = plane.FlightRegion,
                    IsAvailable = plane.IsAvailable,
                    Manufacturer = plane.Manufacturer,
                    Type = plane.Type,
                    AirMiles = plane.AirMiles,
                    ConstructionYear = plane.ConstructionYear,
                    FlightHours = plane.FlightHours,
                    NextMainentance = plane.NextMainentance,
                }) ;
            }

            return View(thislist);
        }

        [Authorize(Roles = "Admin")]
        //ADMIN ROLE
        public async Task<IActionResult> List(string option, string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
            List<PlaneListViewModel> thislist = new List<PlaneListViewModel>();
            foreach (var plane in planeEntities)
            {
                thislist.Add(new PlaneListViewModel()
                {
                    PlaneNr = plane.PlaneNr,
                    CurrentAirline = plane.CurrentAirline,
                    PassengerCapacity = plane.PassengerCapacity,
                    FlightRegion = plane.FlightRegion,
                    IsAvailable = plane.IsAvailable,
                    Manufacturer = plane.Manufacturer,
                    Type = plane.Type,
                    AirMiles = plane.AirMiles,
                    ConstructionYear = plane.ConstructionYear,
                    FlightHours = plane.FlightHours,
                    NextMainentance = plane.NextMainentance,
                });
            }
            //searchfunction
            var myPlane = from s in thislist
                          select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                if (option == "Name")
                {
                    myPlane = myPlane.Where(s => s.PlaneNr.Contains(searchString));
                }
                else if (option == "Type")
                {
                    myPlane = myPlane.Where(s => s.Type.Contains(searchString));
                }
                else if (option == "Capacity")
                {
                    myPlane = myPlane.Where(s => s.PassengerCapacity.ToString().Contains(searchString)).ToList();
                }
                else if (option == "Date")
                {
                    myPlane = myPlane.Where(s => s.ConstructionYear.ToString("dd/MM/yyyy").Contains(searchString) || s.ConstructionYear.ToString("dd-MM-yyyy").Contains(searchString)).ToList();
                }
            }
            return View(myPlane.ToList());
        }

        [Authorize(Roles = "Admin")]
        //ADMIN
        [HttpGet]
        public IActionResult Create()
        {
            var planeCreateViewModel  = new PlaneCreateViewModel();
            if (planesToAdd.Count != 0)
            {
                planeCreateViewModel = planesToAdd[0];
            }
                      
            return View(planeCreateViewModel);
        }

        [Authorize(Roles = "Airline")]
        //Airline
        [HttpGet]
        public IActionResult AddPlane(Airline ID)
        {
            var planeCreateViewModel = planesToAdd[0];
            planeCreateViewModel.CurrentAirline = ID;
            return View(planeCreateViewModel);
        }

        [Authorize(Roles = "Admin, Airline")]
        //AIRLINE + ADMIN
        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public async Task<IActionResult> Create(PlaneCreateViewModel planeViewModel)
        {
            await Task.Delay(1500);
            if (LoggedInAirline == null)
            {

                LoggedInAirline = new Airline
                {
                    Name = "Harald Airways",
                };
                LoggedInAirline = airlineEntities.FirstOrDefault(x => x.Name == LoggedInAirline.Name);


            }

            if (LoggedInAirline.CurrentPlanes == null)
            {
                LoggedInAirline.CurrentPlanes = new List<Plane>();
            }
            planeViewModel.CurrentAirline = LoggedInAirline;
            var isValid = TryValidateModel(planeViewModel);
            Random generator = new Random();
            if (isValid)
            {
                //UniqueCOmbo with Meaning

                string tempPlaneNr = planeViewModel.CurrentAirline.NameTag + DateTime.Now.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture) + generator.Next(0, 100).ToString() + planeViewModel.FlightRegion;
                var newEntity = new Plane
                {
                    
                    PlaneNr = tempPlaneNr,
                    FlightRegion = planeViewModel.FlightRegion,      
                    CurrentAirline = planeViewModel.CurrentAirline,
                    PassengerCapacity = planeViewModel.PassengerCapacity,
                    FuelUsagePerKM = planeViewModel.FuelUsagePerKM,
                    FirstClassCapacity = planeViewModel.FirstClassCapacity,                   
                    FuelCapacity = planeViewModel.FuelCapacity,
                    IsAvailable = planeViewModel.IsAvailable,
                    LoadCapacity = planeViewModel.LoadCapacity,
                    Manufacturer = planeViewModel.Manufacturer,
                    Type = planeViewModel.Type  ,
                    SeatDiagramPic = planeViewModel.SeatDiagramPic,
                    AirMiles = planeViewModel.AirMiles,
                    ConstructionYear = planeViewModel.ConstructionYear,
                    FlightHours = planeViewModel.FlightHours,
                    NextMainentance = planeViewModel.NextMainentance,

                };
                planesToAdd.Clear();
                planeEntities.Add(newEntity);
                _myDatabase.AddPlane(newEntity);
                //planeEntities = _myDatabase.GetPlanes();
                //airlineEntities = _myDatabase.GetAirlines();
                return RedirectToAction("Index", newEntity.CurrentAirline.AirlineID);
            }
            return View(planeViewModel);
        }

        [Authorize(Roles = "Admin, Airline")]
        //AIRLINE + ADMIN
        [HttpGet]
        public IActionResult Detail(string ID)
        {
            ID = ID.Replace("%2F", "/");
            var thisPlane = planeEntities.FirstOrDefault(x => x.PlaneNr == ID);
            var planeDetailViewModel = new PlaneDetailViewModel()
            {
                PlaneNr = thisPlane.PlaneNr,
                FlightRegion = thisPlane.FlightRegion,
                CurrentAirline = thisPlane.CurrentAirline,
                PassengerCapacity = thisPlane.PassengerCapacity,
                FuelUsagePerKM = thisPlane.FuelUsagePerKM,
                FirstClassCapacity = thisPlane.FirstClassCapacity,
                FuelCapacity = thisPlane.FuelCapacity,
                IsAvailable = thisPlane.IsAvailable,
                LoadCapacity = thisPlane.LoadCapacity,

AirWaze/Views/Plane/AddPlane.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model PlaneCreateViewModel

<link rel="stylesheet" href="~/css/planecreate.css">

<main>
    <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center ">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center pt-50">
                            <h2>New Airplane</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br/>
        <div class="col-lg-9" style="padding-bottom: 50px;">
            <h3 class="font-weight-bold" style="padding-top: 50px; padding-bottom: 30px;">Add New Plane</h3>   
<div style="padding-top:200px;"></div>
<form asp-controller="Plane" asp-action="Create" method="post">
    <div class="form-group" >
        <label asp-for="Type"></label>
        <input class ="form-control" asp-for="Type" readonly="readonly"/>
        <span class="text-danger" asp-validation-for="Type"></span>
    </div>
    
    <div class="form-group">
        <label asp-for="Manufacturer" ></label>
        <input class ="form-control" asp-for="Manufacturer" readonly="readonly"/>
        <span class="text-danger" asp-validation-for="Manufacturer"></span>
    </div>
    <div class="form-group"  hidden="hidden">
        <label asp-for="SeatDiagramPic" ></label>
        <input class ="form-control" asp-for="SeatDiagramPic" />
        <span class="text-danger" asp-validation-for="SeatDiagramPic"></span>
    </div>
    <div class="form-group">
        <label asp-for="PassengerCapacity"></label>
        <input class ="form-control" asp-for="PassengerCapacity" readonly="readonly"/>
        <span class="text-danger" asp-validation-for="PassengerCapacity"></span>
    </div> 
    <div class="form-group">
        <label asp-for="FirstClassCapacity"></label>
        <input class ="form-control" asp-for="FirstClassCapacity" readonly="readonly" />
        <span class="text-danger" asp-validation-for="FirstClassCapacity"></span>
    </div>
    <div class="form-group">
        <label asp-for="FuelCapacity">Fuel Capacity in Liters</label>
        <input class ="form-control" asp-for="FuelCapacity" readonly="readonly"/>
        <span class="text-danger" asp-validation-for="FuelCapacity"></span>
    </div>
    
    <div class="form-group">
        <label asp-for="LoadCapacity">Load Capacity in Kg</label>
        <input class ="form-control" asp-for="LoadCapacity" readonly="readonly"/>
        <span class="text-danger" asp-validation-for="LoadCapacity"></span>
    </div>
    <div class="form-group">
        <label asp-for="FuelUsagePerKM">Fuel Usage Liters/KM</label>
        <input class ="form-control" asp-for="FuelUsagePerKM" readonly="readonly"/>
        <span class="text-danger" asp-validation-for="FuelUsagePerKM"></span>
    </div>
    <div class="form-group">
        <label asp-for="FlightRegion"></label>
        <input class ="form-control" asp-for="FlightRegion" readonly="readonly"/>
        <span class="text-danger" asp-validation-for="FlightRegion"></span>
    </div>
     <div class="form-group">
        <label asp-for="ConstructionYear"></label>
        <input class ="form-control" asp-for="ConstructionYear" />
        <span class="text-danger" asp-validation-for="ConstructionYear"></span>
    </div>
    <div class="form-group">
        <label asp-for="AirMiles">Km in the Air for this Airport</label>
        <input class ="form-control" asp-for="AirMiles" />
        <span class="text-danger" asp-validation-for="AirMiles"></span>
    </div>
    <div class="form-group" hidden="hidden">
        <label asp-for="FlightHours"></label>
        <input class ="form-control" asp-for="FlightHours" />
        <span class="text-danger" asp-validation-for="AirMiles"></span>
    </div>
     <div class="form-group" hidden="hidden">
        <label asp-for="NextMainentance"></label>
        <input class ="form-control" asp-for="NextMainentance" />
        <span class="text-danger" asp-validation-for="NextMainentance"></span>
    </div>
       <div class="form-group">
        <input asp-for="IsAvailable"/>
        <label asp-for="IsAvailable">Currently Available?</label>
    
    </div>
    

    <button class="btn btn-secondary" type="submit" onclick="message()" style="margin-top:50px;margin-left:40%;width:400px;">Create</button> 
</form>
</div>

<script type="text/javascript">
        function message()
        {
            Swal.fire({                   
                    position: 'center',
                    icon: 'success',
                    title: 'Plane Added',
                    showConfirmButton: false,
                    timer: 1500                   
                    });
        }
    </script>

AirWaze/Views/Plane/Create.cshtml
@model PlaneCreateViewModel

<head>
    <link rel="stylesheet" href="~/css/planecreate.css">
</head>
<div style="padding-top:200px;"></div>
<form asp-controller="Plane" asp-action="Create" method="post">
    <div class="form-group" >
        <label asp-for="Type"></label>
        <input class ="form-control" asp-for="Type" readonly="readonly"/>
        <span class="text-danger" asp-validation-for="Type"></span>
    </div>
    
    <div class="form-group">
        <label asp-for="Manufacturer" ></label>
        <input class ="form-control" asp-for="Manufacturer" readonly="readonly"/>
        <span class="text-danger" asp-validation-for="Manufacturer"></span>
    </div>
    <div class="form-group"  hidden="hidden">
        <label asp-for="SeatDiagramPic" ></label>
        <input class ="form-control" asp-for="SeatDiagramPic" />
        <span class="text-danger" asp-validation-for="SeatDiagramPic"></span>
    </div>
    <div class="form-group">
        <label asp-for="PassengerCapacity"></label>
        <input class ="form-control" asp-for="PassengerCapacity" readonly="readonly"/>
        <span class="text-danger" asp-validation-for="PassengerCapacity"></span>
    </div> 
    <div class="form-group">
        <label asp-for="FirstClassCapacity"></label>
        <input class ="form-control" asp-for="FirstClassCapacity" readonly="readonly" />
        <span class="text-danger" asp-validation-for="FirstClassCapacity"></span>
    </div>
    <div class="form-group">
        <label asp-for="FuelCapacity">Fuel Capacity in Liters</label>
        <input class ="form-control" asp-for="FuelCapacity" />
        <span class="text-danger" asp-validation-for="FuelCapacity"></span>
    </div>
    
    <div class="form-group">
        <label asp-for="LoadCapacity">Load Capacity in Kg</label>
        <input class ="form-control" asp-for="LoadCapacity" />
        <span class="text-danger" asp-validation-for="LoadCapacity"></span>
    </div>
    <div class="form-group">
        <label asp-for="FuelUsagePerKM">Fuel Usage Liters/KM</label>
        <input class ="form-control" asp-for="FuelUsagePerKM" />
        <span class="text-danger" asp-validation-for="FuelUsagePerKM"></span>
    </div>
    <div class="form-group">
        <label asp-for="FlightRegion"></label>
        <input class ="form-control" asp-for="FlightRegion" />
        <span class="text-danger" asp-validation-for="FlightRegion"></span>
    </div>
     <div class="form-group">
        <label asp-for="ConstructionYear"></label>
        <input class ="form-control" asp-for="ConstructionYear" />
        <span class="text-danger" asp-validation-for="ConstructionYear"></span>
    </div>
    <div class="form-group">
        <label asp-for="AirMiles">Km in the Air for this Airport</label>
        <input class ="form-control" asp-for="AirMiles" />
        <span class="text-danger" asp-validation-for="AirMiles"></span>
    </div>
    <div class="form-group" hidden="hidden">
        <label asp-for="FlightHours"></label>
        <input class ="form-control" asp-for="FlightHours" />
        <span class="text-danger" asp-validation-for="AirMiles"></span>
    </div>
     <div class="form-group" hidden="hidden">
        <label asp-for="NextMainentance"></label>
        <input class ="form-control" asp-for="NextMainentance" />
        <span class="text-danger" asp-validation-for="NextMainentance"></span>
    </div>
       <div class="form-group">
        <input asp-for="IsAvailable"/>
        <label asp-for="IsAvailable">Currently Available?</label>
    
    </div>
    

    <button class="btn btn-secondary" type="submit" onclick="message()" style="margin-top:50px;margin-left:40%;width:400px;">Create</button> 
</form>

<script type="text/javascript">
        function message()
        {
            Swal.fire({                   
                    position: 'center',
                    icon: 'success',
                    title: 'Plane Added',
                    showConfirmButton: false,
                    timer: 1500                 
                    });
        }
    </script>

AirWaze/Views/Plane/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model PlaneDeleteViewModel
    
}

 <head>
    <link rel="stylesheet" href="~/css/Detailplaneair.css" asp-append-version="true" />
</head>

<div style="padding-top:200px;"></div>
<div class="peoples-visit dining-padding-top">           
            <div class="single-visit left-img">
                <div class="container">
                    <div class="row justify-content-end">
                        <div class="col-lg-8">
                            <div class="visit-caption" style="background-color:#ce9244;">
                                <span>Delete @Model.PlaneNr?</span>
                                <ul>                                                                       
                                    <br />
                                    <li>@Model.PlaneNr</li>                                                                      
                                    <li>@Model.CurrentAirline.Name</li>
                                    <li>@Model.Manufacturer</li>
                                    <li>@Model.Type</li>                                    
                                </ul>
                                <br />
                                <h1>Delete this Plane?</h1>
                                <br />
                                 <a class="genric-btn info-border circle arrow" onclick="message()" asp-controller="Plane" asp-action="DeleteConfirm" asp-route-ID="@Model.PlaneNr" style="margin-left:10px;">Ja<span class="lnr lnr-arrow-right"></span></a>
                                 <a class="genric-btn danger-border circle arrow" asp-controller="Plane" asp-action="Index" style="margin-left:10px;">Neen<span class="lnr lnr-arrow-right"></span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
  
    <script type="text/javascript">
        function message()
        {
            Swal.fire({                   
                    position: 'center',
                    icon: 'error',
                    title: 'Plane Deleted',
                    showConfirmButton: false,
                    timer: 1500                   
                    });
        }
    </script>

AirWaze/Views/Plane/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string path = @Model.SeatDiagramPic.Remove(0,1);
    path = path.Insert(0, "..");
}
@model PlaneDetailViewModel


 <head>
    <link rel="stylesheet" href="~/css/Detailplane.css" asp-append-version="true" />            
</head>
<div style="padding-top:200px;"></div>
<div class="peoples-visit dining-padding-top">           
            <div class="single-visit left-img">               
                <div class="container">
                    <div class="row justify-content-end">
                        <div class="col-lg-8">
                            <div class="visit-caption" style="background-color:#36b1ad;">
                                <span>Details for @Model.PlaneNr</span>
                                <form asp-controller="Plane" asp-action="Create" method="post">
                                <div class="form-group" >
                                    <label asp-for="Type"></label>
                                    <input class ="form-control" asp-for="Type" readonly="readonly"/>
                                    <span class="text-danger" asp-validation-for="Type"></span>
                                </div>
    
                                <div class="form-group">
                                    <label asp-for="Manufacturer" ></label>
                                    <input class ="form-control" asp-for="Manufacturer" readonly="readonly"/>
                                    <span class="text-danger" asp-validation-for="Manufacturer"></span>
                                </div>                               
                                <div class="form-group">
                                    <label asp-for="PassengerCapacity"></label>
                                    <input class ="form-control" asp-for="PassengerCapacity" readonly="readonly"/>
                                    <span class="text-danger" asp-validation-for="PassengerCapacity"></span>
                                </div> 
                                <div class="form-group">
                                    <label asp-for="FirstClassCapacity"></label>
                                    <input class ="form-control" asp-for="FirstClassCapacity" readonly="readonly" />
                                    <span class="text-danger" asp-validation-for="FirstClassCapacity"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="FuelCapacity">Fuel Capacity in Liters</label>
                                    <input class ="form-control" asp-for="FuelCapacity" readonly="readonly"/>
                                    <span class="text-danger" asp-validation-for="FuelCapacity"></span>
                                </div>
    
                                <div class="form-group">
                                    <label asp-for="LoadCapacity">Load Capacity in Kg</label>
                                    <input class ="form-control" asp-for="LoadCapacity" readonly="readonly"/>
                                    <span class="text-danger" asp-validation-for="LoadCapacity"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="FuelUsagePerKM">Fuel Usage Liters/KM</label>
                                    <input class ="form-control" asp-for="FuelUsagePerKM" readonly="readonly"/>
                                    <span class="text-danger" asp-validation-for="FuelUsagePerKM"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="FlightRegion"></label>
                                    <input class ="form-control" asp-for="FlightRegion" readonly="readonly"/>
                                    <span class="text-danger" asp-validation-for="FlightRegion"></span>
                                </div>
                                 <div class="form-group">
                                    <label asp-for="ConstructionYear"></label>
                                    <input class ="form-control" asp-for="ConstructionYear"  readonly="readonly"/>
                                    <span class="text-danger" asp-validation-for="ConstructionYear"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="AirMiles">Km in the Air for this Airport</label>
                                    <input class ="form-control" asp-for="AirMiles"  readonly="readonly"/>
                                    <span class="text-danger" asp-validation-for="AirMiles"></span>
                                </div>
                               
                                   <div class="form-group">
                                    <input asp-for="IsAvailable"  readonly="readonly"/>
                                    <label asp-for="IsAvailable">Currently Available?</label>  
                                </div>     
                                <a class="genric-btn info-border circle" asp-action="Index" asp-controller="Airline">Back</a>
                            </form>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 

AirWaze/Views/Plane/Index.cshtml
@using AirWaze.Controllers
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model List<PlaneListViewModel> 
    
}

<head>
	 <link rel="stylesheet" href="~/css/planeindex.css">
</head>
<div style="padding-top:200px;"></div>
<div class="planeindexcontainer">
@if (Model.Count != 0)
{
    <div class="progress-table-wrap">
						<div class="progress-table">
							<div class="table-head">
								<div class="serial">Nr</div>
								<div class="visit" style="padding-left:20px;">Capacity</div>
								<div class="visit" style="padding-left:80px;">Region</div>
								<div class="visit" style="padding-left:60px;">Manfufacturer</div>
								<div class="visit" style="padding-left:60px;">Type</div>
								<div class="visit" style="padding-left:60px;">ConstructionYear</div>
								<div class="percentage"></div>
								<div class="percentage"></div>
								<div class="percentage"></div>
							</div>
							 @foreach (var plane in Model)
							{
								<div class="table-row">
									<div class="serial">@plane.PlaneNr</div>
									<div class="visit" style="padding-left:20px;">@plane.PassengerCapacity</div>
									<div class="visit" style="padding-left:20px;">@plane.FlightRegion</div>
									<div class="visit" style="padding-left:20px;">@plane.Manufacturer</div>
									<div class="visit" style="padding-left:20px;">@plane.Type</div>
									<div class="visit" style="padding-left:20px;">@plane.ConstructionYear</div>
									<div class="visit" style="padding-left:20px"><a class="genric-btn info circle arrow" asp-action="Detail" asp-controller="Plane" asp-route-ID=@plane.PlaneNr>Detail</a></div>
									<div class="visit" style="padding-left:20px"><a class="genric-btn warning circle arrow" asp-action="Update" asp-controller="Plane" asp-route-ID=@plane.PlaneNr>Edit</a></div>
									<div class="visit" style="padding-left:20px"><a class="genric-btn danger circle arrow" asp-action="Delete" asp-controller="Plane" asp-route-ID=@plane.PlaneNr>Delete</a></div>									
								</div>						
							}
                          </div>
    </div>
}
 else
    {
        <h1>No Planes Currently Available</h1>
    }
<div style="margin:100px;">
 <a class="genric-btn primary e-large" asp-area="" asp-controller="Plane" asp-action="Type" style="margin-left:250px;width:600px;">Add New Plane</a>
</div> 
</div>

AirWaze/Views/Plane/Type.cshtml
@using AirWaze.Components
@{
    ViewData["Title"] = "Home Page";
}

<link rel="stylesheet" href="~/css/airplanetype.css">

<main>
    <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center ">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center pt-50">
                            <h2>New Airplane</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br/>
        <div class="col-lg-9" style="padding-bottom: 50px;">
            <h2 class="font-weight-bold" style="padding-top: 50px; padding-bottom: 30px;">Airplane Type</h2>
            @* <script src="_content/Blazor.Extensions.Canvas/blazor.extensions.canvas.js"></script>*@
            <script src="_framework/blazor.server.js"></script>
            @(await Html.RenderComponentAsync<Planetypepicker>(RenderMode.Server))
        </div>
</main>