AirWaze/Entities/Ticket.cs
using AirWaze.Areas.Identity.Data;
using System.ComponentModel.DataAnnotations;

namespace AirWaze.Entities
{
    public class Ticket
    {
        [Key]
        public int TicketID { get; set; }
        public string TicketNr { get; set; }
        public Flight CurrentFlight { get; set; }
        public ApplicationUser CurrentUser { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public decimal Price { get; set; }
        public bool FirstClass { get; set; }
        public string Seat { get; set; }
        public bool ExtraLuggage { get; set; }
        public int Status { get; set; }
        /* 
         * 0 = generated, not paid
         * 1 = generated, paid
         * 2 = checked in
         * 3 = boarded
         * 4 = refunded (customer request)
         * 5 = cancelled (airport request)
         */
    }
}

AirWaze/Models/Ticket/TicketCreateViewModel.cs
using AirWaze.Entities;
using System.ComponentModel.DataAnnotations;

namespace AirWaze.Models
{
    public class TicketCreateViewModel
    {
        public string? TicketNr { get; set; }

        [Required(ErrorMessage = "A departure time must be selected!")]
        public DateTime Departure { get; set; }

        [Required(ErrorMessage = "A destination must be selected!")]
        public string Destination { get; set; }

        [MinLength(1, ErrorMessage = "Minimum 1 character!")]
        [MaxLength(20, ErrorMessage = "Maximum 20 characters!")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Last name is required!")]
        public string LastName { get; set; }

        [MinLength(1, ErrorMessage = "Minimum 1 character!")]
        [MaxLength(20, ErrorMessage = "Maximum 20 characters!")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "First name is required!")]
        public string FirstName { get; set; }
        public decimal Price { get; set; }
        public bool FirstClass { get; set; }
        public string? Seat { get; set; }
        public bool ExtraLuggage { get; set; }
    }
}

AirWaze/Models/Ticket/TicketDeleteViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class TicketDeleteViewModel
    {
        public string TicketNr { get; set; }
        public Flight CurrentFlight { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
    }
}

AirWaze/Models/Ticket/TicketDetailViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class TicketDetailViewModel
    {
        public string TicketNr { get; set; }
        public Flight CurrentFlight { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public decimal Price { get; set; }
        public bool FirstClass { get; set; }
        public string Seat { get; set; }
        public bool ExtraLuggage { get; set; }
    }
}

AirWaze/Models/Ticket/TicketEditViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class TicketEditViewModel
    {
        public string TicketNr { get; set; }
        public Flight CurrentFlight { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public decimal Price { get; set; }
        public bool FirstClass { get; set; }
        public string Seat { get; set; }
        public bool ExtraLuggage { get; set; }
    }
}

AirWaze/Models/Ticket/TicketFlightPickerViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class TicketFlightPickerViewModel
    {
        public List<Flight> flightList { get; set; }

        public string TicketNr { get; set; }
    }
}

AirWaze/Models/Ticket/TicketListViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class TicketListViewModel
    {
        public string TicketNr { get; set; }
        public Flight CurrentFlight { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int Status { get; set; }
    }
}

AirWaze/Models/Ticket/TicketPaymentViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class TicketPaymentViewModel
    {
        public string TicketNr { get; set; }
        public Flight CurrentFlight { get; set; }
        public bool FirstClass { get; set; }
        public bool ExtraLuggage { get; set; }
        public decimal Price { get; set; }
    }
}

AirWaze/Controllers/TicketController.cs
using AirWaze.Areas.Identity.Data;
using AirWaze.Database.Design;
using AirWaze.Entities;
using AirWaze.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace AirWaze.Controllers
{
    [Authorize(Roles = "Admin, Customer")]
    public class TicketController : Controller
    {
        private readonly UserManager<AirWazeUser> _userManager;
        private readonly IAirWazeDatabase database;
        private static List<Ticket> loadedTickets = new List<Ticket>();
        public static List<Destination> allDestinations = new List<Destination>();
        public static List<Flight> allFlights = new List<Flight>();
        public static List<TicketCreateViewModel> ticketsToHandle = new List<TicketCreateViewModel>();
        static ApplicationUser myUser;

        public TicketController(IAirWazeDatabase db, UserManager<AirWazeUser> userManager)
        {
            _userManager = userManager;
            database = db;
            if(allDestinations.Count == 0)
            {
                allDestinations = database.GetDestinations();
            }
            
            //myUser = HttpContext.User;
            //myUser = database.GetUserByID(HttpContext.Session.GetString("user_id"));
            
        }

        public async void GetUser()
        {
            string myUserId = _userManager.GetUserId(User);
            myUser = database.GetUserByID(myUserId);
            if (loadedTickets.Count == 0)
            {
                LoadTicketList(myUser);
            }
        }

       

        


        public IActionResult Index()
        {
            GetUser();
            return View();
        }

        public IActionResult List(string option, string searchString)
        {
            ViewData["CurrentFilter"] = searchString;
            GetUser();
            List<TicketListViewModel> list = new List<TicketListViewModel>();
            foreach (var ticket in loadedTickets)
            {
                if (ticket.CurrentUser.Id == myUser.Id)
                {
                    list.Add(new TicketListViewModel()
                    {
                        TicketNr = ticket.TicketNr,
                        CurrentFlight = ticket.CurrentFlight,
                        LastName = ticket.LastName,
                        FirstName = ticket.FirstName,
                        Status = ticket.Status
                    });
                }
            }
            //searchfunction
            var myTicket = from s in list
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                if (option == "Destination")
                {
                    myTicket = myTicket.Where(s => s.CurrentFlight.Destination.Name.Contains(searchString));
                }
                else if (option == "Date")
                {
                    myTicket = myTicket.Where(s => s.CurrentFlight.Departure.ToString("dd/MM/yyyy").Contains(searchString) || s.CurrentFlight.Departure.ToString("dd-MM-yyyy").Contains(searchString)).ToList();
                }
                else if (option == "Name")
                {
                    myTicket = myTicket.Where(s => s.LastName.Contains(searchString) || s.FirstName.Contains(searchString));
                }
            }
            return View(myTicket.ToList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new TicketCreateViewModel());
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Create(TicketCreateViewModel newTicket)
        {
            await Task.Delay(1500);
            if (TryValidateModel(newTicket))
            {
                newTicket.TicketNr = $"NOTASSIGNED{ticketsToHandle.Count}";
                ticketsToHandle.Add(newTicket);
                LoadTicketList(myUser);
                return Redirect($"FlightPicker/{newTicket.TicketNr}");
            }
            return View(newTicket);
        }

        [HttpGet]
        [Route("Ticket/FlightPicker/{ticketNr}")]
        public IActionResult FlightPicker(string ticketNr)
        {
            TicketCreateViewModel toHandle = ticketsToHandle.Single(x => x.TicketNr == ticketNr);
            TicketFlightPickerViewModel flightPicker = new TicketFlightPickerViewModel()
            {
                flightList = database.GetFlightsByDate(toHandle.Departure, 3),
                TicketNr = ticketNr
            };

            if(flightPicker.flightList.Count > 0)
            {
                return View(flightPicker);
            }
            else
            {
                ticketsToHandle.Remove(toHandle);
                return RedirectToAction("Create", toHandle);
            }           
        }

        public IActionResult Detail(string ID)
        {
            Ticket loadedTicket = loadedTickets.Single(x => x.TicketNr == ID);
            TicketDetailViewModel detailTicket = new TicketDetailViewModel()
            {
                TicketNr = loadedTicket.TicketNr,
                CurrentFlight = loadedTicket.CurrentFlight,
                LastName = loadedTicket.LastName,
                FirstName = loadedTicket.FirstName,
                Price = loadedTicket.Price,
                FirstClass = loadedTicket.FirstClass,
                Seat = loadedTicket.Seat,
                ExtraLuggage = loadedTicket.ExtraLuggage
            };
            return View(detailTicket);
        }

        [HttpGet]
        public IActionResult Edit(string ID)
        {
            Ticket loadedTicket = loadedTickets.Single(x => x.TicketNr == ID);
            TicketEditViewModel editTicket = new TicketEditViewModel()
            {
                TicketNr = loadedTicket.TicketNr,
                CurrentFlight = loadedTicket.CurrentFlight,
                LastName = loadedTicket.LastName,
                FirstName = loadedTicket.FirstName,
                Price = loadedTicket.Price,
                FirstClass = loadedTicket.FirstClass,
                Seat = loadedTicket.Seat,
                ExtraLuggage = loadedTicket.ExtraLuggage,
            };
            return View(editTicket);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Edit(string ID, TicketEditViewModel editedTicket)
        {
            await Task.Delay(1500);
            Ticket loadedTicket = loadedTickets.Single(x => x.TicketNr == ID);
            loadedTicket.LastName = editedTicket.LastName;
            loadedTicket.FirstName = editedTicket.FirstName;
            database.UpdateTicket(loadedTicket);
            return RedirectToAction("List");
        }

        public IActionResult Delete(string ID)
        {
            Ticket loadedTicket = loadedTickets.Single(x => x.TicketNr == ID);
            TicketDeleteViewModel deleteTicket = new TicketDeleteViewModel()
            {
                TicketNr = loadedTicket.TicketNr,
                CurrentFlight = loadedTicket.CurrentFlight,
                LastName = loadedTicket.LastName,
                FirstName = loadedTicket.FirstName
            };
            LoadTicketList(myUser);
            return View(deleteTicket);
        }

        public async Task<IActionResult> ConfirmedDelete(string ID)
        {
            await Task.Delay(1500);
            database.RemoveTicket(loadedTickets.Single(x => x.TicketNr == ID));
            LoadTicketList(myUser);
            return RedirectToAction("List");
        }

        public IActionResult Payment(string ID, string ticket)
        {
            TicketCreateViewModel toHandle = ticketsToHandle.Single(x => x.TicketNr == ticket);
            Flight chosenFlight = database.GetFlightByNr(ID);
            string ticketnr = GenerateTicketNumber(chosenFlight);
            string seat = GenerateSeatNumber(chosenFlight);
            toHandle.Price = toHandle.FirstClass ? (toHandle.ExtraLuggage ? chosenFlight.Destination.Distance * (decimal)1.2 + 75 : chosenFlight.Destination.Distance * (decimal)1.2) : (toHandle.ExtraLuggage ? chosenFlight.Destination.Distance + 75 : chosenFlight.Destination.Distance);

            loadedTickets.Add(new Ticket()
            {
                TicketNr = ticketnr,
                CurrentFlight = chosenFlight,
                CurrentUser = myUser,
                LastName = toHandle.LastName,
                FirstName = toHandle.FirstName,
                Price = toHandle.Price,
                FirstClass = toHandle.FirstClass,
                Seat = seat,
                ExtraLuggage = toHandle.ExtraLuggage,
                Status = 0
            });
            TicketPaymentViewModel payTicket = new TicketPaymentViewModel()
            {
                TicketNr = ticketnr,
                CurrentFlight = chosenFlight,
                Price = toHandle.Price,
                FirstClass = toHandle.FirstClass,
                ExtraLuggage = toHandle.ExtraLuggage
            };
            return View(payTicket);
        }

        public IActionResult ConfirmedPayment(string ID)
        {
            Ticket newTicket = loadedTickets.Single(x => x.TicketNr == ID);
            newTicket.Status = 1;
            if(database.AddTicket(newTicket) <= 0)
            {
                LoadTicketList(myUser);
            }
            
            return RedirectToAction("Index");
        }

        public IActionResult FailedPayment(TicketCreateViewModel newTicket)
        {

            return RedirectToAction("Create", newTicket);
        }

        public string GenerateTicketNumber(Flight flight)
        {
            return Guid.NewGuid().ToString();
        }

        public string GenerateSeatNumber(Flight flight)
        {
            return flight.FillSeatDiagram(1);
        }

        public void LoadTicketList(ApplicationUser user)
        {

AirWaze/Views/Ticket/Create.cshtml
@using AirWaze.Controllers
@using AirWaze.Entities
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model TicketCreateViewModel
<main>
<form asp-controller="Ticket" asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="LastName">Last Name</label>
        <input class="form-control" asp-for="LastName"/>
        <span class="text-danger" asp-validation-for="LastName"></span>
    </div>
    <div class="form-group">
        <label asp-for="FirstName">First Name</label>
        <input class="form-control" asp-for="FirstName"/>
        <span class="text-danger" asp-validation-for="FirstName"></span>
    </div>
    <p>Flight Information</p>
    <div class="form-group">
        <label>Available Destinations:</label>
        <br />
        <select name="Destination">
            @foreach(var item in @TicketController.allDestinations)
            {
                 <option value=@item.Name>@item.Name</option>
            }
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Confirm Plane</button>
    <div class="form-group">
        <label asp-for="FirstClass">Preferred time of departure</label>
        <input asp-for="Departure"/>
    </div>


    <div class="form-group">
        <input asp-for="FirstClass"/>
        <label asp-for="FirstClass">First Class?</label>
    </div>
    <div class="form-group">
        <input asp-for="ExtraLuggage"/>
        <label asp-for="ExtraLuggage">Extra Luggage?</label>
    </div>

    <button class="btn btn-primary" onclick="message()" type="submit">Create Ticket</button>
</form>
</main>
<script type="text/javascript">
        function message()
        {
            Swal.fire({                   
                    position: 'center',
                    icon: 'success',
                    title: 'Ticket Created',
                    showConfirmButton: false,
                    timer: 1500                 
                    });
        }
    </script>

AirWaze/Views/Ticket/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model TicketDeleteViewModel
<main>
<h1>Cancelling your ticket</h1>
<h2>Ticket Information</h2>
<p>Name: @Model.LastName @Model.FirstName</p>
<p>Flight Destination: @Model.CurrentFlight.Destination</p>
<p>Flight Departure: @Model.CurrentFlight.Departure</p>

<a class="btn btn-danger" onclick="message()" asp-action="ConfirmedDelete" asp-route-ID="@Model.TicketNr">Cancel Ticket</a>
<a class="btn btn-primary" asp-action="List">Go Back</a>
</main>
<script type="text/javascript">
        function message()
        {
            Swal.fire({                   
                    position: 'center',
                    icon: 'error',
                    title: 'Ticket Deleted',
                    showConfirmButton: false,
                    timer: 1500                 
                    });
        }
    </script>

AirWaze/Views/Ticket/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model TicketDetailViewModel
<main>
<h1>Ticket @Model.TicketNr</h1>
<p>Name: @Model.LastName @Model.FirstName</p>
<p>Destination: @Model.CurrentFlight.Destination</p>
<p>Departure: @Model.CurrentFlight.Departure</p>
<p>Airline: @Model.CurrentFlight.CurrentPlane.CurrentAirline.Name</p>
<p>Seat: @Model.Seat</p>
@if (Model.FirstClass)
    {
        <p>Class: First Class</p>
    }
    else
    {
        <p>Class: Economy</p>
    }
@if (Model.ExtraLuggage)
    {
        <p>Extra Luggage: Yes</p>
    }
    else
    {
        <p>Extra Luggage: No</p>
    }
<p>Price: @Model.Price</p>

<a class="btn btn-primary" asp-controller="Ticket" asp-action="Index">Return</a>
<a class="btn btn-primary" asp-controller="Ticket" asp-action="Edit" asp-route-ID="@Model.TicketNr">Change Passenger Information</a>
<a class="btn btn-danger" asp-controller="Ticket" asp-action="Delete" asp-route-ID="@Model.TicketNr">Delete</a>
</main>

AirWaze/Views/Ticket/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model TicketEditViewModel
<main>
<h1>Change Ticket @Model.TicketNr</h1>

<form asp-controller="Ticket" asp-action="Edit" method="post">
    <div class="form-group">
        <label asp-for="LastName">Last Name</label>
        <input class="form-control" asp-for="LastName"/>
        <span class="text-danger" asp-validation-for="LastName"></span>
    </div>
    <div class="form-group">
        <label asp-for="FirstName">First Name</label>
        <input class="form-control" asp-for="FirstName"/>
        <span class="text-danger" asp-validation-for="FirstName"></span>
    </div>

    <button class="btn btn-primary" onclick="message()" type="submit">Save Ticket</button>
</form>
</main>
<script type="text/javascript">
        function message()
        {
            Swal.fire({                   
                    position: 'center',
                    icon: 'success',
                    title: 'Ticket Modified',
                    showConfirmButton: false,
                    timer: 1500                 
                    });
        }
    </script>

AirWaze/Views/Ticket/FlightPicker.cshtml
@using AirWaze.Entities
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model TicketFlightPickerViewModel
<main>
<table>
    <tr>
        <th>Destination</th>
        <th>Departure time</th>
    </tr>
    @foreach (var flight in Model.flightList)
    {
        <tr>
            <td>@flight.Destination</td>
            <td>@flight.Departure</td>
            <td><a asp-action="Payment" asp-route-ID="@flight.FlightNr" asp-route-ticket="@Model.TicketNr">Select</a></td>
        </tr>
    }
</table>
<a class="btn btn-primary" asp-action="Create">Go Back</a>
</main>

AirWaze/Views/Ticket/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<main>
<a asp-action="Create">New Ticket</a>
<a asp-action="List">All Tickets</a>
</main>

AirWaze/Views/Ticket/List.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<TicketListViewModel>

<main>
<div>
  @*searchfunction*@
    <form asp-action="List" method="get">
        <div class="form-actions no-color">
            <p>
                Search by: &nbsp;
                @Html.RadioButton("option", "Name") Name &nbsp;
                @Html.RadioButton("option", "Destination") Destination &nbsp;
                @Html.RadioButton("option", "Date") Date &nbsp; &nbsp;*
                <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" /> &nbsp;
                <input class="btn btn-primary" type="submit" value="Search"/> &nbsp;
                <a href="/Ticket/List" class="btn btn-primary">Show all tickets</a> 
            </p>
        </div>
    </form>
    <br/>
    <table>
        <tr>
            <th>Ticket Number</th>
            <th>Name</th>
            <th>Status</th>
        </tr>
        @foreach(var ticket in Model)
        {
            <tr>
                <td>@ticket.TicketNr</td>
                <td>@ticket.LastName @ticket.FirstName</td>
                <td>@ticket.Status</td>
                <td><a class="btn btn-primary" asp-action="Detail" asp-route-ID="@ticket.TicketNr">Details</a></td>
            </tr>
        }

    </table>
</div>

AirWaze/Views/Ticket/Payment.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model TicketPaymentViewModel

<main>
<h1>Payment</h1>
<p>Destination: @Model.CurrentFlight.Destination</p>
<p>Departure: @Model.CurrentFlight.Departure</p>
<p>First Class: @if (Model.FirstClass) { <p>yes</p> } else { <p>no</p> }
<p>Extra Luggage: @if (Model.ExtraLuggage) { <p>yes</p> } else { <p>no</p> }
<h2>Total Price: € @Model.Price</h2>

<a class="btn btn-primary" asp-action="ConfirmedPayment" asp-route-ID="@Model.TicketNr">Pay Now</a>
<a class="btn btn-primary" asp-action="Edit" asp-route-ID="@Model.TicketNr">Change Ticket</a>
<a class="btn btn-danger" asp-action="Delete" asp-route-ID="@Model.TicketNr">Abort</a>
</main>