AirWaze/Entities/Flight.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AirWaze.Entities
{
    public class Flight
    {
        [Key]
        public int FlightID { get; set; }
        public string FlightNr { get; set; }
        public Plane? CurrentPlane { get; set; }
        public bool CurrentPlaneConfirmed { get; set; }

        public DateTime Departure { get; set; }
        public Destination Destination { get; set; }
        public Gate CurrentGate { get; set; }
        public Runway CurrentRunway { get; set; }
        public int Status { get; set; }
        /* 
          0 = Generated, Not Approved
          1 = Approved
          2 = Delayed
          3 = Boarding
          4 = Departed
          5 = Arrived
          6 = Cancelled
          7 = Completed (Plane has returned)
         */
        public string? SeatDiagram { get; set; }

        public override string ToString()
        {
            return $"{Destination} {Departure}";
        }

        public string FillSeatDiagram(int seatsToAdd)
        {
            if(SeatDiagram != null)
            {
                int seatCounter = 0;
                int rowCounter = 0;
                bool isFound = false;
                for(int i = 0; i < SeatDiagram.Length; i++)
                {
                    switch (SeatDiagram[i])
                    {
                        case '0': //free seat
                            SeatDiagram = SeatDiagram.Remove(i, 1).Insert(i, "1");
                            isFound = true;
                            break;
                        case '-': //break between rows
                            seatCounter = 0;
                            rowCounter++;
                            break;
                        default: //any other option
                            seatCounter++;
                            break;
                    }
                    if (isFound) //empty seat
                    {
                        break;
                    }
                }
                string seatNr = "";
                seatNr += (rowCounter+1).ToString();
                switch (seatCounter)
                {
                    case 0:
                        seatNr += "A";
                        break;
                    case 1:
                        seatNr += "B";
                        break;
                    case 2:
                        seatNr += "C";
                        break;
                    case 3:
                        seatNr += "D";
                        break;
                    case 4:
                        seatNr += "E";
                        break;
                    case 5:
                        seatNr += "F";
                        break;
                    case 6:
                        seatNr += "G";
                        break;
                    case 7:
                        seatNr += "H";
                        break;
                }
                return seatNr;
            }
            return null;
        }
    }
}

AirWaze/Models/Flight/FlightCreateViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class FlightCreateViewModel
    {
        public int FlightID { get; set; }
        public string? FlightNr { get; set; }
        public Plane? CurrentPlane { get; set; }
        public DateTime Departure { get; set; }
        public Destination? Destination { get; set; }
        public Gate? CurrentGate { get; set; }
        public Runway? CurrentRunway { get; set; }
        public int Status { get; set; }
    }
}

AirWaze/Models/Flight/FlightDeleteViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class FlightDeleteViewModel
    {
        public int FlightID { get; set; }
        public string FlightNr { get; set; }
        public DateTime Departure { get; set; }
        public Destination Destination { get; set; }
        public int Status { get; set; }
    }
}

AirWaze/Models/Flight/FlightDetailViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class FlightDetailViewModel
    {
        public int FlightID { get; set; }
        public string FlightNr { get; set; }
        public Plane CurrentPlane { get; set; }
        public DateTime Departure { get; set; }
        public Destination Destination { get; set; }
        public Gate CurrentGate { get; set; }
        public Runway CurrentRunway { get; set; }
        public int Status { get; set; }
    }
}

AirWaze/Models/Flight/FlightEditViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class FlightEditViewModel
    {
        public int FlightID { get; set; }
        public string FlightNr { get; set; }
        public Plane CurrentPlane { get; set; }
        public DateTime Departure { get; set; }
        public Destination Destination { get; set; }
        public Gate? CurrentGate { get; set; }
        public Runway? CurrentRunway { get; set; }
        public int Status { get; set; }
    }
}

AirWaze/Models/Flight/FlightListViewModel.cs
using AirWaze.Entities;

namespace AirWaze.Models
{
    public class FlightListViewModel
    {
        public int FlightID { get; set; }
        public string FlightNr { get; set; }
        public DateTime Departure { get; set; }
        public Destination Destination { get; set; }
        public Gate CurrentGate { get; set; }
        public int Status { get; set; }
    }
}

AirWaze/Models/Flight/FlightTempViewModel.cs
namespace AirWaze.Models
{
    public class FlightTempViewModel
    {
        public TimeSpan FlightTime { get; set; }
        public DateTime Departure { get; set; }
        public decimal Distance { get; set; }
        public string? Destination { get; set; }
    }
}

AirWaze/Controllers/FlightController.cs
using AirWaze.Database.Design;
using AirWaze.Database;
using AirWaze.Entities;
using AirWaze.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AirWaze.Controllers
{
    public class FlightController : Controller
    {
        public readonly IAirWazeDatabase _airwazeDatabase;
        public static List<Flight> flights = new List<Flight>();
        public static List<FlightCreateViewModel> tempFlightModels = new List<FlightCreateViewModel>();
        Random _random = new Random();
        public static List<Destination> destinations = new List<Destination>();

        //testplane (and linked testAirline) is used for new FlightCreateViewModels, before going to PlanePicker
        static Airline testAirline = new Airline
        {
            Number = "00000",
            PhoneNumber = "XXXXXXXXXX",
            CurrentPlanes = new List<Plane>(),
            AccountNumber = "XXXXXXXX",
            Adress = "Teststraat",
            City = "Test",
            AirlineID = Guid.NewGuid(),
            CompanyNumber = "1111111",
            Email = "test@email.com",
            Name = "TestAirWays",
            NameTag = "TEST",
        };
        static Plane testplane = new Plane
        {
            PlaneNr = "TestPlane",
            CurrentAirline = testAirline,
            PassengerCapacity = 1,
            FuelUsagePerKM = 1,
            FirstClassCapacity = 1,
            FlightRegion = "EUR",
            FuelCapacity = 1,
            IsAvailable = true,
            LoadCapacity = 1,
            Manufacturer = "Tester",
            Type = "111",
        };
        public FlightController(IAirWazeDatabase airwazeDatabase)
        {
            _airwazeDatabase = airwazeDatabase;
            //List<Flight> oldlist = flights.ToList();
            //if (flights.Count == 0)
            //{
            //    flights = _airwazeDatabase.GetFlights();
            //}
            //else
            //{
            //    foreach (Flight x in flights)
            //    {
            //        foreach (Flight y in oldlist)
            //        {
            //            if (x.FlightID == y.FlightID)
            //            {
            //                if (x.Status != y.Status)
            //                {
            //                    x.Status = y.Status;
            ////_airwazeDatabase.UpdateFlight(x);
            //            }
            //        }
            //    }

            //}
            ////planes = _airwazeDatabase.GetPlanes();
            //}
        }

        //Roles: Everyone
        [HttpGet]
        public IActionResult Index(string option, string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            var flightViewModels = new List<FlightListViewModel>();

            foreach (var flight in flights)
            {
                flightViewModels.Add(new FlightListViewModel()
                {
                    FlightID = flight.FlightID,
                    FlightNr = flight.FlightNr,
                    Departure = flight.Departure,
                    Destination = flight.Destination,
                    CurrentGate = flight.CurrentGate,
                    Status = flight.Status
                });
            }
            //searchfunction
            var myFlight = from s in flightViewModels
                            select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                if (option == "Destination")
                {
                    myFlight = myFlight.Where(s => s.Destination.Name.Contains(searchString));
                }
                else if (option == "Date")
                {
                    myFlight = myFlight.Where(s => s.Departure.ToString("dd/MM/yyyy").Contains(searchString) || s.Departure.ToString("dd-MM-yyyy").Contains(searchString)).ToList();
                }
            }
            return View(myFlight.OrderBy(x => x.Departure).ToList());
        }


        //Roles: everyone
        [HttpGet]
        [Route("Flight/Detail/{id}")]
        public IActionResult Detail(string id)
        {
            var flightEntity = flights.FirstOrDefault(x => x.FlightNr == id);

            if (flightEntity != null)
            {
                var flightDetails = new FlightDetailViewModel()
                {
                    FlightID = flightEntity.FlightID,
                    FlightNr = flightEntity.FlightNr,
                    CurrentPlane = flightEntity.CurrentPlane,
                    Departure = flightEntity.Departure,
                    Destination = flightEntity.Destination,
                    CurrentGate = flightEntity.CurrentGate,
                    CurrentRunway = flightEntity.CurrentRunway,
                    Status = flightEntity.Status
                };
                return View(flightDetails);
            }
            return View();
        }

        [Authorize(Roles = "Admin")]
        //Roles: Admin + Airport Staff
        [HttpGet]
        public IActionResult Create()
        {
            var flightViewModel = new FlightCreateViewModel();
            return View(flightViewModel);
        }

        [Authorize(Roles = "Admin")]
        //Roles: Admin + Airport Staff
        [HttpGet]
        public IActionResult CreateAgain(string id)
        {
            var flightViewModel = tempFlightModels.FirstOrDefault(x => x.FlightNr == id);
            return View("Create",flightViewModel);
        }

        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Create(FlightCreateViewModel flightViewModel)
        {
            await Task.Delay(1500);
            flightViewModel.Destination = destinations.FirstOrDefault(x => x.Name == Request.Form["selectedDestination"]);
            flightViewModel.FlightNr = CreateFlightNr(flightViewModel);
            flightViewModel.CurrentGate = _airwazeDatabase.GetGateByNr(0);
            flightViewModel.CurrentPlane = testplane;
            flightViewModel.CurrentRunway = _airwazeDatabase.GetRunwayByNr(0);
            flightViewModel.Status = 0;

            if (TryValidateModel(flightViewModel))
            {
                tempFlightModels.Add(flightViewModel);   
                return RedirectToAction("PlanePicker", new { flightNr = flightViewModel.FlightNr });
            }
            else
            {
                return View(flightViewModel);
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        //[Route("Flight/PlanePicker/{flightNr}")]
        public IActionResult PlanePicker(string flightNr)
        {
            var flightCreateViewModel = tempFlightModels.SingleOrDefault(x => x.FlightNr == flightNr);
            
            return View(flightCreateViewModel);      
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult PlanePicker(FlightCreateViewModel flightViewModel, string id)
        {
            flightViewModel = tempFlightModels.SingleOrDefault(x => x.FlightNr == id);
            flightViewModel.CurrentPlane = PlaneController.planeEntities.FirstOrDefault(x => x.PlaneNr == Request.Form["selectedPlaneNr"]);

            if (TryValidateModel(flightViewModel))
            {
                var newEntity = new Flight
                {
                    FlightID = flightViewModel.FlightID,
                    FlightNr = flightViewModel.FlightNr,
                    CurrentPlane = flightViewModel.CurrentPlane,
                    Departure = flightViewModel.Departure,
                    Destination = flightViewModel.Destination,
                    CurrentGate = flightViewModel.CurrentGate,
                    CurrentRunway = flightViewModel.CurrentRunway,
                    Status = flightViewModel.Status
                };
                _airwazeDatabase.AddFlight(newEntity);
                flights.Add(newEntity);
                Airport.Flights.Add(newEntity);
                tempFlightModels.Remove(flightViewModel);
                return RedirectToAction("Index");
            }
            else
            {
                return View(flightViewModel);
            }
        }

        [Authorize(Roles = "Admin")]
        //Roles: Admin + Airport Staff
        [HttpGet]
        public IActionResult Edit(string id)
        {
            var flightEntity = flights.FirstOrDefault(x => x.FlightNr == id);

            if (flightEntity == null) return new NotFoundResult();

            var flightEdit = new FlightEditViewModel()
            {
                FlightID = flightEntity.FlightID,
                FlightNr = flightEntity.FlightNr,
                CurrentPlane = flightEntity.CurrentPlane,
                Departure = flightEntity.Departure,
                Destination = flightEntity.Destination,
                CurrentGate = flightEntity.CurrentGate,
                CurrentRunway = flightEntity.CurrentRunway,
                Status = flightEntity.Status
            };

            return View(flightEdit);
        }

        [Authorize(Roles = "Admin")]
        //Roles: Admin + Airport Staff
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Edit(string id, FlightEditViewModel flightViewModel)
        {
            await Task.Delay(1500);
            flightViewModel.CurrentPlane = PlaneController.planeEntities.FirstOrDefault(x => x.PlaneNr == Request.Form["selectedPlaneNr"]);
            flightViewModel.CurrentGate = Airport.Gates.FirstOrDefault(x => x.Number == Convert.ToInt32(Request.Form["selectedGate"]));
            flightViewModel.CurrentRunway = Airport.Runways.FirstOrDefault(x => x.Number == Convert.ToInt32(Request.Form["selectedRunway"]));
            flightViewModel.FlightNr = id;
            flightViewModel.Destination = flights.FirstOrDefault(x => x.FlightNr == id).Destination;

AirWaze/Views/Flight/Create.cshtml
@using AirWaze.Controllers
@using AirWaze.Models
@using AirWaze.Entities
@model FlightCreateViewModel

@{
    List<Destination> allDestinations = FlightController.destinations.OrderBy(dest => dest.Region).ThenBy(dest => dest.Name).ToList();
}
<main>
<h1>Create New Flight</h1>

<form asp-controller="Flight" asp-action="Create" method="post">
    
 <div class="form-group">
        <label>Destination:</label>
        <select name="selectedDestination">
            @foreach(var item in allDestinations)
            {
                    if(@Model.Destination != null)
                    {
                        if(@Model.Destination.Name == item.Name)
                        {
                                <option selected value=@item.Name>@item.Region  - @item.Name</option>
                        }
                        else
                        {
                            <option value=@item.Name>@item.Region  - @item.Name</option>
                        }
                    }
                    else
                    {
                        <option value=@item.Name>@item.Region  - @item.Name</option>
                    }
            }
        </select>
    </div>
    <br />


    <div class="form-group">
        <label asp-for="Departure"></label>
        <input class="form-control" asp-for="Departure" />
        <span asp-validation-for="Departure"></span>
    </div>
     <br />



     <a class="btn btn-primary" asp-controller="Flight" asp-action="Index">Go Back</a>
    <button class="btn btn-primary" onclick="message()" type="submit">Create Flight</button>
</form>
<script type="text/javascript">
        function message()
        {
            Swal.fire({                   
                    position: 'center',
                    icon: 'success',
                    title: 'Flight Created',
                    showConfirmButton: false,
                    timer: 1500                   
                    });
        }
    </script>
    </main>

AirWaze/Views/Flight/Delete.cshtml
@model FlightDeleteViewModel
<main>
<p>Are you sure you want to delete Flight @Model.FlightNr?</p>
<br />
<p>Destination: @Model.Destination.Name - Departure: @Model.Departure.ToString("R")</p>
@switch(@Model.Status)
{
    case 0:
            <p>Status: Awaiting Approval</p>
            break;
    case 1:
        <p>Status: Approved</p>
        break;
    case 2:
        <p>Status: Delayed</p>
        break;
    case 3:
        <p>Status: Boarding</p>
        break;
    case 4:
        <p>Status: Departed</p>
        break;
    case 5:
        <p>Status: Arrived</p>
        break;
    case 6:
        <p>Status: Cancelled</p>
        break;
    case 7:
        <p>Status: Completed</p>
        break;
    default:
        break;
}

<a asp-controller="Flight" asp-action="Index">Go Back</a>
<a class="btn btn-danger" onclick="message()" asp-controller="Flight" asp-action="DeleteConfirm" asp-route-id="@Model.FlightNr">Delete</a>

<script type="text/javascript">
        function message()
        {
            Swal.fire({                   
                    position: 'center',
                    icon: 'error',
                    title: 'Flight Deleted',
                    showConfirmButton: false,
                    timer: 1500                   
                    });
        }
    </script>
    </main>

AirWaze/Views/Flight/Detail.cshtml
@model FlightDetailViewModel

<main>
<h1>Flight Details</h1>

<!-- Possible Notifications: Delayed?, Cancelled, Boarding, In Transit, Arrived At Destination, Fully Booked -->
<!-- Calculate -->
<h2>Flight Number</h2>
<p>@Model.FlightNr</p>
<h2>Destination</h2>
<p>@Model.Destination.Name</p>
<h2>Airline</h2>
<p>@Model.CurrentPlane.CurrentAirline.Name</p>
<h2>Departure</h2>
<p>@Model.Departure.ToString("R")</p>
<h2></h2>
<h2>Flight Duration (hh:mm)</h2>
<p>@Model.Destination.FlightTime</p>
<h2>Distance</h2>
<p>@Model.Destination.Distance km</p>
<h2>Gate</h2>
@if(Model.CurrentGate.Number == 0)
{
    <p>No Gate assigned yet.</p>
}
else
{
    <p>@Model.CurrentGate.Number</p>
}
<h2>Current Status</h2>
@switch (Model.Status)
            {
                case 0:
                    <p>Awaiting Approval</p>
                    break;
                case 1:
                    <p>Approved</p>
                    break;
                case 2:
                    <p>Delayed</p>
                    break;
                case 3:
                    <p>Boarding</p>
                    break;
                case 4:
                    <p>Departed</p>
                    break;
                case 5:
                    <p>Arrived</p>
                    break;
                case 6:
                    <p>Cancelled</p>
                    break;
                default:
                    break;
            }

<!-- For Airport staff-->
<h2>Plane</h2>
<p>@Model.CurrentPlane.PlaneNr</p>
<h2>Runway</h2>
@if(Model.CurrentRunway.Number == 0)
{
    <p>No Runway assigned yet.</p>
}
else
{
    <p>@Model.CurrentRunway.Number</p>
}
<!-- TODO: route button to page with tickets only for this flight 
<a class="btn btn-primary" asp-controller="Ticket" asp-action="Index">Booked Tickets</a>
-->
<a class="btn btn-primary" asp-controller="Flight" asp-action="Index">Go Back</a>

</main>

AirWaze/Views/Flight/Edit.cshtml
@using AirWaze.Controllers
@using AirWaze.Entities
@model FlightEditViewModel

@{
    List<Destination> allDestinations = FlightController.destinations.OrderBy(dest => dest.Region).ThenBy(dest => dest.Name).ToList();

    List<Plane> availablePlanesForThisFlight = Airport.GetAvailablePlanesForFlight(Airport.Flights.SingleOrDefault(x => x.FlightNr == Model.FlightNr)).ToList();
}
<main style="margin-top: 200px">
<h1>Edit Flight Details</h1>
<h2>for Flight Nr.: @Model.FlightNr</h2>
<br />

<form asp-controller="Flight" asp-action="Edit" asp-route-id="@Model.FlightNr" method="post">
 <div class="form-group">
        <label>Destination: @Model.Destination.Name (@Model.Destination.Region)</label>
    </div>
    <br />

    <!-- look up fill in datetimepicker with value -->
    <div class="form-group">
        <label asp-for="Departure"></label>
        <input class="form-control" asp-for="Departure"/>
        <span asp-validation-for="Departure"></span>
    </div>
     <br />


     <div class="form-group">
        <label>Gate</label>
        <br />
        <select name="selectedGate">
            @foreach(Gate gate in Airport.Gates)
            {
                    if(gate.Number == Model.CurrentGate.Number)
                    {
                        if(gate.Number == 0)
                        {
                            <option value="@gate.Number" selected>@gate.Number - None Assigned Yet</option>
                        }
                        else
                        {
                            <option value="@gate.Number" selected>@gate.Number</option>
                        }
                    }
                    else
                    {
                        if(gate.Number == 0)
                        {
                            <option value="@gate.Number">@gate.Number - None Assigned Yet</option>
                        }
                        else
                        {
                            <option value="@gate.Number">@gate.Number</option>
                        }
                    }
            }
         </select>
    </div>
     <br />

    <div class="form-group">
        <label>Runway</label>
        <br />
        <select name="selectedRunway">
            @foreach(Runway runway in Airport.Runways)
            {
                 if(@runway.Number == @Model.CurrentRunway.Number)
                    {
                        if(@runway.Number == 0)
                        {
                            <option selected value="@runway.Number">@runway.Number - None Assigned Yet</option>
                        }
                        else
                        {
                            <option selected value="@runway.Number">@runway.Number</option>
                        }
                    }
                    else
                    {
                        if(runway.Number == 0)
                        {
                            <option value="@runway.Number">@runway.Number - None Assigned Yet</option>
                        }
                        else
                        {
                            <option value="@runway.Number">@runway.Number</option>
                        }
                    }
            }
         </select>
    </div>
     <br />

     <div class="form-group">
        <label>Plane</label>
        <br />
        <select name="selectedPlaneNr">
            @foreach(var item in @availablePlanesForThisFlight)
            {
                if(@item.PlaneNr == @Model.CurrentPlane.PlaneNr)
                {
                        <option value="@item.PlaneNr" selected>@item.CurrentAirline.Name - @item.PlaneNr</option>
                    }
                    else
                    {
                                            <option value="@item.PlaneNr">@item.CurrentAirline.Name - @item.PlaneNr</option>
                    }
            }
        </select>
    </div>

     <div class="form-group">
        <label>Status</label>
        <br />
        <select name="selectedStatus">
            @if(Model.Status == 0)
            {
                <option value=0 selected>0 - Awaiting Approval</option>
            }
            else
            {
                    <option value=0>0 - Awaiting Approval</option>
                }
                 @if(Model.Status == 1)
            {
                <option value=1 selected>1 - Approved</option>
            }
            else
            {
                    <option value=1>1 - Approved</option>
                }
                @if(Model.Status == 2)
            {
                <option value=2 selected>2 - Delayed</option>
            }
            else
            {
                    <option value=2>2 - Delayed</option>
                }
                 @if(Model.Status == 3)
            {
                <option value=3 selected>3 - Boarding</option>
            }
            else
            {
                     <option value=3>3 - Boarding</option>
                }
               @if(Model.Status == 4)
            {
                <option value=4 selected>4 - Departed</option>
            }
            else
            {
                     <option value=4>4 - Departed</option>
                }  
                @if(Model.Status == 5)
            {
                <option value=5 selected>5 - Arrived</option>
            }
            else
            {
                     <option value=5>5 - Arrived</option>
                }  
                 @if(Model.Status == 6)
            {
                 <option value=6 selected>6 - Cancelled</option>
            }
            else
            {
                     <option value=6>6 - Cancelled</option>
                }  
                 @if(Model.Status == 7)
            {
                 <option value=7 selected>7 - Completed</option>
            }
            else
            {
                     <option value=7>7 - Completed</option>
                }  
        </select>
    </div>
     <a class="btn btn-primary" asp-controller="Flight" asp-action="Index">Go Back</a>
    <button class="btn btn-primary" onclick="message()" type="submit">Edit Flight</button>
</form>
<script type="text/javascript">
        function message()
        {
            Swal.fire({                   
                    position: 'center',
                    icon: 'success',
                    title: 'FLight Modified',
                    showConfirmButton: false,
                    timer: 1500                   
                    });
        }
    </script>
    </main>

AirWaze/Views/Flight/PlanePicker.cshtml
@using AirWaze.Controllers
@using AirWaze.Entities
@model FlightCreateViewModel

<!-- add method to make list of available planes for that flight - check flight region (destination), and Departure date/time -->
@{
    Flight tempFlight = new Flight
            {
                Destination = Model.Destination,
                Departure = Model.Departure
            };
    List<Plane> availablePlanesForThisFlight = Airport.GetAvailablePlanesForFlight(tempFlight).ToList();
}

<main>
@if(availablePlanesForThisFlight.Count > 0)
{
    <h2>Please select the plane for this flight</h2>
<form asp-controller="Flight" asp-action="PlanePicker" asp-route-id=@Model.FlightNr method="post">

 <div class="form-group">
        <label>Available Planes:</label>
        <br />
        <select name="selectedPlaneNr">
            @foreach(var item in availablePlanesForThisFlight)
            {
                 <option value=@item.PlaneNr>@item.CurrentAirline.Name  - @item.PlaneNr</option>
            }
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Confirm Plane</button>
    </form>
}
else
{
    <h2>There are currently no planes available for this flight.</h2>
    <p>Please select another Departure Time.</p>

    <a class="btn btn-primary" asp-controller="Flight" asp-action="CreateAgain" asp-route-id="@Model.FlightNr">Go Back</a>
}
</main>